# -*- coding: utf-8 -*-
from random import randint
# Form implementation generated from reading ui file 'ui.ui'
#mm
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
def toss(faces=6): 
    return randint(1,faces)

def system_iaros(counter, value_plus):
    values_toss=[]
    for i in range(counter):
        val = toss()
        if(val + value_plus >6):
            values_toss.append(val)
    return len(values_toss)
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 872)
        font = QtGui.QFont()
        font.setPointSize(7)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: #e7f5dc")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.poko = QtWidgets.QLabel(self.centralwidget)
        self.poko.setGeometry(QtCore.QRect(40, 370, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.poko.setFont(font)
        self.poko.setStyleSheet("background-color: #4b6154;\n"
"color:white;\n"
"border: 2px solid #c0dfc2; \n"
"border-radius: 10px;  ")
        self.poko.setAlignment(QtCore.Qt.AlignCenter)
        self.poko.setObjectName("poko")
        self.poko_tablo = QtWidgets.QLabel(self.centralwidget)
        self.poko_tablo.setGeometry(QtCore.QRect(170, 370, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.poko_tablo.setFont(font)
        self.poko_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.poko_tablo.setStyleSheet("background-color: #4b6154\n"
"")
        self.poko_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.poko_tablo.setObjectName("poko_tablo")
        self.poko_down = QtWidgets.QPushButton(self.centralwidget)
        self.poko_down.setGeometry(QtCore.QRect(230, 390, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.poko_down.setFont(font)
        self.poko_down.setStyleSheet("background-color:#94d6ba")
        self.poko_down.setObjectName("poko_down")
        self.poko_up = QtWidgets.QPushButton(self.centralwidget)
        self.poko_up.setGeometry(QtCore.QRect(230, 370, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.poko_up.setFont(font)
        self.poko_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.poko_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.poko_up.setObjectName("poko_up")
        self.survival_up = QtWidgets.QPushButton(self.centralwidget)
        self.survival_up.setGeometry(QtCore.QRect(230, 430, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.survival_up.setFont(font)
        self.survival_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.survival_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.survival_up.setObjectName("survival_up")
        self.survival_down = QtWidgets.QPushButton(self.centralwidget)
        self.survival_down.setGeometry(QtCore.QRect(230, 450, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.survival_down.setFont(font)
        self.survival_down.setStyleSheet("background-color:#94d6ba")
        self.survival_down.setObjectName("survival_down")
        self.survival_tablo = QtWidgets.QLabel(self.centralwidget)
        self.survival_tablo.setGeometry(QtCore.QRect(170, 430, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.survival_tablo.setFont(font)
        self.survival_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.survival_tablo.setStyleSheet("background-color: #c0dfc2;\n"
"border: 2px solid #4b6154")
        self.survival_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.survival_tablo.setObjectName("survival_tablo")
        self.provorstvo_down = QtWidgets.QPushButton(self.centralwidget)
        self.provorstvo_down.setGeometry(QtCore.QRect(230, 510, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.provorstvo_down.setFont(font)
        self.provorstvo_down.setStyleSheet("background-color:#94d6ba")
        self.provorstvo_down.setObjectName("provorstvo_down")
        self.provorstvo_tablo = QtWidgets.QLabel(self.centralwidget)
        self.provorstvo_tablo.setGeometry(QtCore.QRect(170, 490, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.provorstvo_tablo.setFont(font)
        self.provorstvo_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.provorstvo_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.provorstvo_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.provorstvo_tablo.setObjectName("provorstvo_tablo")
        self.provorstvo_up = QtWidgets.QPushButton(self.centralwidget)
        self.provorstvo_up.setGeometry(QtCore.QRect(230, 490, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.provorstvo_up.setFont(font)
        self.provorstvo_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.provorstvo_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.provorstvo_up.setObjectName("provorstvo_up")
        self.samooblad_down = QtWidgets.QPushButton(self.centralwidget)
        self.samooblad_down.setGeometry(QtCore.QRect(230, 570, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.samooblad_down.setFont(font)
        self.samooblad_down.setStyleSheet("background-color:#94d6ba")
        self.samooblad_down.setObjectName("samooblad_down")
        self.samooblad_tablo = QtWidgets.QLabel(self.centralwidget)
        self.samooblad_tablo.setGeometry(QtCore.QRect(170, 550, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.samooblad_tablo.setFont(font)
        self.samooblad_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.samooblad_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.samooblad_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.samooblad_tablo.setObjectName("samooblad_tablo")
        self.samooblad_up = QtWidgets.QPushButton(self.centralwidget)
        self.samooblad_up.setGeometry(QtCore.QRect(230, 550, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.samooblad_up.setFont(font)
        self.samooblad_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.samooblad_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.samooblad_up.setObjectName("samooblad_up")
        self.threat_down = QtWidgets.QPushButton(self.centralwidget)
        self.threat_down.setGeometry(QtCore.QRect(230, 630, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.threat_down.setFont(font)
        self.threat_down.setStyleSheet("background-color:#94d6ba")
        self.threat_down.setObjectName("threat_down")
        self.threat_tablo = QtWidgets.QLabel(self.centralwidget)
        self.threat_tablo.setGeometry(QtCore.QRect(170, 610, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.threat_tablo.setFont(font)
        self.threat_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.threat_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.threat_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.threat_tablo.setObjectName("threat_tablo")
        self.threat_up = QtWidgets.QPushButton(self.centralwidget)
        self.threat_up.setGeometry(QtCore.QRect(230, 610, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.threat_up.setFont(font)
        self.threat_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.threat_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.threat_up.setObjectName("threat_up")
        self.atletic_down = QtWidgets.QPushButton(self.centralwidget)
        self.atletic_down.setGeometry(QtCore.QRect(230, 690, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.atletic_down.setFont(font)
        self.atletic_down.setStyleSheet("background-color:#94d6ba")
        self.atletic_down.setObjectName("atletic_down")
        self.atletic_tablo = QtWidgets.QLabel(self.centralwidget)
        self.atletic_tablo.setGeometry(QtCore.QRect(170, 670, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.atletic_tablo.setFont(font)
        self.atletic_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.atletic_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.atletic_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.atletic_tablo.setObjectName("atletic_tablo")
        self.atletic_up = QtWidgets.QPushButton(self.centralwidget)
        self.atletic_up.setGeometry(QtCore.QRect(230, 670, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.atletic_up.setFont(font)
        self.atletic_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.atletic_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.atletic_up.setObjectName("atletic_up")
        self.animal_down = QtWidgets.QPushButton(self.centralwidget)
        self.animal_down.setGeometry(QtCore.QRect(230, 750, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.animal_down.setFont(font)
        self.animal_down.setStyleSheet("background-color:#94d6ba")
        self.animal_down.setObjectName("animal_down")
        self.animal_tablo = QtWidgets.QLabel(self.centralwidget)
        self.animal_tablo.setGeometry(QtCore.QRect(170, 730, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.animal_tablo.setFont(font)
        self.animal_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.animal_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.animal_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.animal_tablo.setObjectName("animal_tablo")
        self.animal_up = QtWidgets.QPushButton(self.centralwidget)
        self.animal_up.setGeometry(QtCore.QRect(230, 730, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.animal_up.setFont(font)
        self.animal_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.animal_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.animal_up.setObjectName("animal_up")
        self.survival_button = QtWidgets.QPushButton(self.centralwidget)
        self.survival_button.setGeometry(QtCore.QRect(40, 430, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.survival_button.setFont(font)
        self.survival_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.survival_button.setObjectName("survival_button")
        self.provorstvo_button = QtWidgets.QPushButton(self.centralwidget)
        self.provorstvo_button.setGeometry(QtCore.QRect(40, 490, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.provorstvo_button.setFont(font)
        self.provorstvo_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.provorstvo_button.setObjectName("provorstvo_button")
        self.samooblad_button = QtWidgets.QPushButton(self.centralwidget)
        self.samooblad_button.setGeometry(QtCore.QRect(40, 550, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.samooblad_button.setFont(font)
        self.samooblad_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.samooblad_button.setObjectName("samooblad_button")
        self.threat_button = QtWidgets.QPushButton(self.centralwidget)
        self.threat_button.setGeometry(QtCore.QRect(40, 610, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.threat_button.setFont(font)
        self.threat_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.threat_button.setObjectName("threat_button")
        self.atletic_button = QtWidgets.QPushButton(self.centralwidget)
        self.atletic_button.setGeometry(QtCore.QRect(40, 670, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.atletic_button.setFont(font)
        self.atletic_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.atletic_button.setObjectName("atletic_button")
        self.animal_button = QtWidgets.QPushButton(self.centralwidget)
        self.animal_button.setGeometry(QtCore.QRect(40, 730, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.animal_button.setFont(font)
        self.animal_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.animal_button.setObjectName("animal_button")
        self.pozn_up = QtWidgets.QPushButton(self.centralwidget)
        self.pozn_up.setGeometry(QtCore.QRect(500, 370, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pozn_up.setFont(font)
        self.pozn_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pozn_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.pozn_up.setObjectName("pozn_up")
        self.ezoterica_button = QtWidgets.QPushButton(self.centralwidget)
        self.ezoterica_button.setGeometry(QtCore.QRect(310, 670, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.ezoterica_button.setFont(font)
        self.ezoterica_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.ezoterica_button.setObjectName("ezoterica_button")
        self.history_button = QtWidgets.QPushButton(self.centralwidget)
        self.history_button.setGeometry(QtCore.QRect(310, 610, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.history_button.setFont(font)
        self.history_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.history_button.setObjectName("history_button")
        self.history_down = QtWidgets.QPushButton(self.centralwidget)
        self.history_down.setGeometry(QtCore.QRect(500, 630, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.history_down.setFont(font)
        self.history_down.setStyleSheet("background-color:#94d6ba")
        self.history_down.setObjectName("history_down")
        self.logic_up = QtWidgets.QPushButton(self.centralwidget)
        self.logic_up.setGeometry(QtCore.QRect(500, 730, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.logic_up.setFont(font)
        self.logic_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logic_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.logic_up.setObjectName("logic_up")
        self.logic_tablo = QtWidgets.QLabel(self.centralwidget)
        self.logic_tablo.setGeometry(QtCore.QRect(440, 730, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.logic_tablo.setFont(font)
        self.logic_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logic_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.logic_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.logic_tablo.setObjectName("logic_tablo")
        self.pozn_down = QtWidgets.QPushButton(self.centralwidget)
        self.pozn_down.setGeometry(QtCore.QRect(500, 390, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pozn_down.setFont(font)
        self.pozn_down.setStyleSheet("background-color:#94d6ba")
        self.pozn_down.setObjectName("pozn_down")
        self.learn_up = QtWidgets.QPushButton(self.centralwidget)
        self.learn_up.setGeometry(QtCore.QRect(500, 430, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.learn_up.setFont(font)
        self.learn_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.learn_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.learn_up.setObjectName("learn_up")
        self.proniziat_tablo = QtWidgets.QLabel(self.centralwidget)
        self.proniziat_tablo.setGeometry(QtCore.QRect(440, 490, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.proniziat_tablo.setFont(font)
        self.proniziat_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.proniziat_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.proniziat_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.proniziat_tablo.setObjectName("proniziat_tablo")
        self.ezoterica_down = QtWidgets.QPushButton(self.centralwidget)
        self.ezoterica_down.setGeometry(QtCore.QRect(500, 690, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ezoterica_down.setFont(font)
        self.ezoterica_down.setStyleSheet("background-color:#94d6ba")
        self.ezoterica_down.setObjectName("ezoterica_down")
        self.proniziat_up = QtWidgets.QPushButton(self.centralwidget)
        self.proniziat_up.setGeometry(QtCore.QRect(500, 490, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.proniziat_up.setFont(font)
        self.proniziat_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.proniziat_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.proniziat_up.setObjectName("proniziat_up")
        self.history_up = QtWidgets.QPushButton(self.centralwidget)
        self.history_up.setGeometry(QtCore.QRect(500, 610, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.history_up.setFont(font)
        self.history_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.history_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.history_up.setObjectName("history_up")
        self.ritor_down = QtWidgets.QPushButton(self.centralwidget)
        self.ritor_down.setGeometry(QtCore.QRect(500, 570, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ritor_down.setFont(font)
        self.ritor_down.setStyleSheet("background-color:#94d6ba")
        self.ritor_down.setObjectName("ritor_down")
        self.proniziat_down = QtWidgets.QPushButton(self.centralwidget)
        self.proniziat_down.setGeometry(QtCore.QRect(500, 510, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.proniziat_down.setFont(font)
        self.proniziat_down.setStyleSheet("background-color:#94d6ba")
        self.proniziat_down.setObjectName("proniziat_down")
        self.learn_down = QtWidgets.QPushButton(self.centralwidget)
        self.learn_down.setGeometry(QtCore.QRect(500, 450, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.learn_down.setFont(font)
        self.learn_down.setStyleSheet("background-color:#94d6ba")
        self.learn_down.setObjectName("learn_down")
        self.logic_down = QtWidgets.QPushButton(self.centralwidget)
        self.logic_down.setGeometry(QtCore.QRect(500, 750, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.logic_down.setFont(font)
        self.logic_down.setStyleSheet("background-color:#94d6ba")
        self.logic_down.setObjectName("logic_down")
        self.pozn_tablo = QtWidgets.QLabel(self.centralwidget)
        self.pozn_tablo.setGeometry(QtCore.QRect(440, 370, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.pozn_tablo.setFont(font)
        self.pozn_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pozn_tablo.setStyleSheet("background-color: #4b6154\n"
"")
        self.pozn_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.pozn_tablo.setObjectName("pozn_tablo")
        self.logic_button = QtWidgets.QPushButton(self.centralwidget)
        self.logic_button.setGeometry(QtCore.QRect(310, 730, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.logic_button.setFont(font)
        self.logic_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.logic_button.setObjectName("logic_button")
        self.ritor_up = QtWidgets.QPushButton(self.centralwidget)
        self.ritor_up.setGeometry(QtCore.QRect(500, 550, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ritor_up.setFont(font)
        self.ritor_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ritor_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.ritor_up.setObjectName("ritor_up")
        self.pozn = QtWidgets.QLabel(self.centralwidget)
        self.pozn.setGeometry(QtCore.QRect(310, 370, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.pozn.setFont(font)
        self.pozn.setStyleSheet("background-color: #4b6154;\n"
"color:white;\n"
"border: 2px solid #c0dfc2; \n"
"border-radius: 10px;  ")
        self.pozn.setAlignment(QtCore.Qt.AlignCenter)
        self.pozn.setObjectName("pozn")
        self.ritor_button = QtWidgets.QPushButton(self.centralwidget)
        self.ritor_button.setGeometry(QtCore.QRect(310, 550, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.ritor_button.setFont(font)
        self.ritor_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.ritor_button.setObjectName("ritor_button")
        self.ritor_tablo = QtWidgets.QLabel(self.centralwidget)
        self.ritor_tablo.setGeometry(QtCore.QRect(440, 550, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.ritor_tablo.setFont(font)
        self.ritor_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ritor_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.ritor_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.ritor_tablo.setObjectName("ritor_tablo")
        self.learn_button = QtWidgets.QPushButton(self.centralwidget)
        self.learn_button.setGeometry(QtCore.QRect(310, 430, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.learn_button.setFont(font)
        self.learn_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.learn_button.setObjectName("learn_button")
        self.history_tablo = QtWidgets.QLabel(self.centralwidget)
        self.history_tablo.setGeometry(QtCore.QRect(440, 610, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.history_tablo.setFont(font)
        self.history_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.history_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.history_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.history_tablo.setObjectName("history_tablo")
        self.learn_tablo = QtWidgets.QLabel(self.centralwidget)
        self.learn_tablo.setGeometry(QtCore.QRect(440, 430, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.learn_tablo.setFont(font)
        self.learn_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.learn_tablo.setStyleSheet("background-color: #c0dfc2;\n"
"border: 2px solid #4b6154")
        self.learn_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.learn_tablo.setObjectName("learn_tablo")
        self.ezoterica_tablo = QtWidgets.QLabel(self.centralwidget)
        self.ezoterica_tablo.setGeometry(QtCore.QRect(440, 670, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.ezoterica_tablo.setFont(font)
        self.ezoterica_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ezoterica_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.ezoterica_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.ezoterica_tablo.setObjectName("ezoterica_tablo")
        self.ezoterica_up = QtWidgets.QPushButton(self.centralwidget)
        self.ezoterica_up.setGeometry(QtCore.QRect(500, 670, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ezoterica_up.setFont(font)
        self.ezoterica_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ezoterica_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.ezoterica_up.setObjectName("ezoterica_up")
        self.proniziat_button = QtWidgets.QPushButton(self.centralwidget)
        self.proniziat_button.setGeometry(QtCore.QRect(310, 490, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.proniziat_button.setFont(font)
        self.proniziat_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.proniziat_button.setObjectName("proniziat_button")
        self.save_up = QtWidgets.QPushButton(self.centralwidget)
        self.save_up.setGeometry(QtCore.QRect(780, 370, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.save_up.setFont(font)
        self.save_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.save_up.setObjectName("save_up")
        self.focus_button = QtWidgets.QPushButton(self.centralwidget)
        self.focus_button.setGeometry(QtCore.QRect(590, 670, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.focus_button.setFont(font)
        self.focus_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.focus_button.setObjectName("focus_button")
        self.empatia_button = QtWidgets.QPushButton(self.centralwidget)
        self.empatia_button.setGeometry(QtCore.QRect(590, 610, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.empatia_button.setFont(font)
        self.empatia_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.empatia_button.setObjectName("empatia_button")
        self.empatia_down = QtWidgets.QPushButton(self.centralwidget)
        self.empatia_down.setGeometry(QtCore.QRect(780, 630, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.empatia_down.setFont(font)
        self.empatia_down.setStyleSheet("background-color:#94d6ba")
        self.empatia_down.setObjectName("empatia_down")
        self.nature_up = QtWidgets.QPushButton(self.centralwidget)
        self.nature_up.setGeometry(QtCore.QRect(780, 730, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nature_up.setFont(font)
        self.nature_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nature_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.nature_up.setObjectName("nature_up")
        self.nature_tablo = QtWidgets.QLabel(self.centralwidget)
        self.nature_tablo.setGeometry(QtCore.QRect(720, 730, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.nature_tablo.setFont(font)
        self.nature_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nature_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.nature_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.nature_tablo.setObjectName("nature_tablo")
        self.save_down = QtWidgets.QPushButton(self.centralwidget)
        self.save_down.setGeometry(QtCore.QRect(780, 390, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.save_down.setFont(font)
        self.save_down.setStyleSheet("background-color:#94d6ba")
        self.save_down.setObjectName("save_down")
        self.medic_up = QtWidgets.QPushButton(self.centralwidget)
        self.medic_up.setGeometry(QtCore.QRect(780, 430, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.medic_up.setFont(font)
        self.medic_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.medic_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.medic_up.setObjectName("medic_up")
        self.relig_tablo = QtWidgets.QLabel(self.centralwidget)
        self.relig_tablo.setGeometry(QtCore.QRect(720, 490, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.relig_tablo.setFont(font)
        self.relig_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.relig_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.relig_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.relig_tablo.setObjectName("relig_tablo")
        self.focus_down = QtWidgets.QPushButton(self.centralwidget)
        self.focus_down.setGeometry(QtCore.QRect(780, 690, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.focus_down.setFont(font)
        self.focus_down.setStyleSheet("background-color:#94d6ba")
        self.focus_down.setObjectName("focus_down")
        self.relig_up = QtWidgets.QPushButton(self.centralwidget)
        self.relig_up.setGeometry(QtCore.QRect(780, 490, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.relig_up.setFont(font)
        self.relig_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.relig_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.relig_up.setObjectName("relig_up")
        self.empatia_up = QtWidgets.QPushButton(self.centralwidget)
        self.empatia_up.setGeometry(QtCore.QRect(780, 610, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.empatia_up.setFont(font)
        self.empatia_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.empatia_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.empatia_up.setObjectName("empatia_up")
        self.fraud_down = QtWidgets.QPushButton(self.centralwidget)
        self.fraud_down.setGeometry(QtCore.QRect(780, 570, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.fraud_down.setFont(font)
        self.fraud_down.setStyleSheet("background-color:#94d6ba")
        self.fraud_down.setObjectName("fraud_down")
        self.relig_down = QtWidgets.QPushButton(self.centralwidget)
        self.relig_down.setGeometry(QtCore.QRect(780, 510, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.relig_down.setFont(font)
        self.relig_down.setStyleSheet("background-color:#94d6ba")
        self.relig_down.setObjectName("relig_down")
        self.medic_down = QtWidgets.QPushButton(self.centralwidget)
        self.medic_down.setGeometry(QtCore.QRect(780, 450, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.medic_down.setFont(font)
        self.medic_down.setStyleSheet("background-color:#94d6ba")
        self.medic_down.setObjectName("medic_down")
        self.nature_down = QtWidgets.QPushButton(self.centralwidget)
        self.nature_down.setGeometry(QtCore.QRect(780, 750, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.nature_down.setFont(font)
        self.nature_down.setStyleSheet("background-color:#94d6ba")
        self.nature_down.setObjectName("nature_down")
        self.save_tablo = QtWidgets.QLabel(self.centralwidget)
        self.save_tablo.setGeometry(QtCore.QRect(720, 370, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.save_tablo.setFont(font)
        self.save_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_tablo.setStyleSheet("background-color: #4b6154\n"
"")
        self.save_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.save_tablo.setObjectName("save_tablo")
        self.nature_button = QtWidgets.QPushButton(self.centralwidget)
        self.nature_button.setGeometry(QtCore.QRect(590, 730, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.nature_button.setFont(font)
        self.nature_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.nature_button.setObjectName("nature_button")
        self.fraud_up = QtWidgets.QPushButton(self.centralwidget)
        self.fraud_up.setGeometry(QtCore.QRect(780, 550, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fraud_up.setFont(font)
        self.fraud_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fraud_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.fraud_up.setObjectName("fraud_up")
        self.save = QtWidgets.QLabel(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(590, 370, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.save.setFont(font)
        self.save.setStyleSheet("background-color: #4b6154;\n"
"color:white;\n"
"border: 2px solid #c0dfc2; \n"
"border-radius: 10px;  ")
        self.save.setAlignment(QtCore.Qt.AlignCenter)
        self.save.setObjectName("save")
        self.fraud_button = QtWidgets.QPushButton(self.centralwidget)
        self.fraud_button.setGeometry(QtCore.QRect(590, 550, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.fraud_button.setFont(font)
        self.fraud_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.fraud_button.setObjectName("fraud_button")
        self.fraud_tablo = QtWidgets.QLabel(self.centralwidget)
        self.fraud_tablo.setGeometry(QtCore.QRect(720, 550, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.fraud_tablo.setFont(font)
        self.fraud_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fraud_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.fraud_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.fraud_tablo.setObjectName("fraud_tablo")
        self.medic_button = QtWidgets.QPushButton(self.centralwidget)
        self.medic_button.setGeometry(QtCore.QRect(590, 430, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.medic_button.setFont(font)
        self.medic_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.medic_button.setObjectName("medic_button")
        self.empatia_tablo = QtWidgets.QLabel(self.centralwidget)
        self.empatia_tablo.setGeometry(QtCore.QRect(720, 610, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.empatia_tablo.setFont(font)
        self.empatia_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.empatia_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.empatia_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.empatia_tablo.setObjectName("empatia_tablo")
        self.medic_tablo = QtWidgets.QLabel(self.centralwidget)
        self.medic_tablo.setGeometry(QtCore.QRect(720, 430, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.medic_tablo.setFont(font)
        self.medic_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.medic_tablo.setStyleSheet("background-color: #c0dfc2;\n"
"border: 2px solid #4b6154")
        self.medic_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.medic_tablo.setObjectName("medic_tablo")
        self.focus_tablo = QtWidgets.QLabel(self.centralwidget)
        self.focus_tablo.setGeometry(QtCore.QRect(720, 670, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.focus_tablo.setFont(font)
        self.focus_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.focus_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.focus_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.focus_tablo.setObjectName("focus_tablo")
        self.focus_up = QtWidgets.QPushButton(self.centralwidget)
        self.focus_up.setGeometry(QtCore.QRect(780, 670, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.focus_up.setFont(font)
        self.focus_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.focus_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.focus_up.setObjectName("focus_up")
        self.relig_button = QtWidgets.QPushButton(self.centralwidget)
        self.relig_button.setGeometry(QtCore.QRect(590, 490, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.relig_button.setFont(font)
        self.relig_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.relig_button.setObjectName("relig_button")
        self.sozid_up = QtWidgets.QPushButton(self.centralwidget)
        self.sozid_up.setGeometry(QtCore.QRect(1060, 370, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sozid_up.setFont(font)
        self.sozid_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sozid_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.sozid_up.setObjectName("sozid_up")
        self.barter_button = QtWidgets.QPushButton(self.centralwidget)
        self.barter_button.setGeometry(QtCore.QRect(870, 670, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.barter_button.setFont(font)
        self.barter_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.barter_button.setObjectName("barter_button")
        self.performance_button = QtWidgets.QPushButton(self.centralwidget)
        self.performance_button.setGeometry(QtCore.QRect(870, 610, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.performance_button.setFont(font)
        self.performance_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.performance_button.setObjectName("performance_button")
        self.performance_down = QtWidgets.QPushButton(self.centralwidget)
        self.performance_down.setGeometry(QtCore.QRect(1060, 630, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.performance_down.setFont(font)
        self.performance_down.setStyleSheet("background-color:#94d6ba")
        self.performance_down.setObjectName("performance_down")
        self.craft_up = QtWidgets.QPushButton(self.centralwidget)
        self.craft_up.setGeometry(QtCore.QRect(1060, 730, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.craft_up.setFont(font)
        self.craft_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.craft_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.craft_up.setObjectName("craft_up")
        self.craft_tablo = QtWidgets.QLabel(self.centralwidget)
        self.craft_tablo.setGeometry(QtCore.QRect(1000, 730, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.craft_tablo.setFont(font)
        self.craft_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.craft_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.craft_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.craft_tablo.setObjectName("craft_tablo")
        self.sozid_down = QtWidgets.QPushButton(self.centralwidget)
        self.sozid_down.setGeometry(QtCore.QRect(1060, 390, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.sozid_down.setFont(font)
        self.sozid_down.setStyleSheet("background-color:#94d6ba")
        self.sozid_down.setObjectName("sozid_down")
        self.fastfinger_up = QtWidgets.QPushButton(self.centralwidget)
        self.fastfinger_up.setGeometry(QtCore.QRect(1060, 430, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fastfinger_up.setFont(font)
        self.fastfinger_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fastfinger_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.fastfinger_up.setObjectName("fastfinger_up")
        self.mecanica_tablo = QtWidgets.QLabel(self.centralwidget)
        self.mecanica_tablo.setGeometry(QtCore.QRect(1000, 490, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.mecanica_tablo.setFont(font)
        self.mecanica_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mecanica_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.mecanica_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.mecanica_tablo.setObjectName("mecanica_tablo")
        self.barter_down = QtWidgets.QPushButton(self.centralwidget)
        self.barter_down.setGeometry(QtCore.QRect(1060, 690, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.barter_down.setFont(font)
        self.barter_down.setStyleSheet("background-color:#94d6ba")
        self.barter_down.setObjectName("barter_down")
        self.mecanica_up = QtWidgets.QPushButton(self.centralwidget)
        self.mecanica_up.setGeometry(QtCore.QRect(1060, 490, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mecanica_up.setFont(font)
        self.mecanica_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mecanica_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.mecanica_up.setObjectName("mecanica_up")
        self.performance_up = QtWidgets.QPushButton(self.centralwidget)
        self.performance_up.setGeometry(QtCore.QRect(1060, 610, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.performance_up.setFont(font)
        self.performance_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.performance_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.performance_up.setObjectName("performance_up")
        self.culture_down = QtWidgets.QPushButton(self.centralwidget)
        self.culture_down.setGeometry(QtCore.QRect(1060, 570, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.culture_down.setFont(font)
        self.culture_down.setStyleSheet("background-color:#94d6ba")
        self.culture_down.setObjectName("culture_down")
        self.mecanica_down = QtWidgets.QPushButton(self.centralwidget)
        self.mecanica_down.setGeometry(QtCore.QRect(1060, 510, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mecanica_down.setFont(font)
        self.mecanica_down.setStyleSheet("background-color:#94d6ba")
        self.mecanica_down.setObjectName("mecanica_down")
        self.fastfinger_down = QtWidgets.QPushButton(self.centralwidget)
        self.fastfinger_down.setGeometry(QtCore.QRect(1060, 450, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.fastfinger_down.setFont(font)
        self.fastfinger_down.setStyleSheet("background-color:#94d6ba")
        self.fastfinger_down.setObjectName("fastfinger_down")
        self.craft_down = QtWidgets.QPushButton(self.centralwidget)
        self.craft_down.setGeometry(QtCore.QRect(1060, 750, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.craft_down.setFont(font)
        self.craft_down.setStyleSheet("background-color:#94d6ba")
        self.craft_down.setObjectName("craft_down")
        self.sozid_tablo = QtWidgets.QLabel(self.centralwidget)
        self.sozid_tablo.setGeometry(QtCore.QRect(1000, 370, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.sozid_tablo.setFont(font)
        self.sozid_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sozid_tablo.setStyleSheet("background-color: #4b6154\n"
"")
        self.sozid_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.sozid_tablo.setObjectName("sozid_tablo")
        self.craft_button = QtWidgets.QPushButton(self.centralwidget)
        self.craft_button.setGeometry(QtCore.QRect(870, 730, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.craft_button.setFont(font)
        self.craft_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.craft_button.setObjectName("craft_button")
        self.culture_up = QtWidgets.QPushButton(self.centralwidget)
        self.culture_up.setGeometry(QtCore.QRect(1060, 550, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.culture_up.setFont(font)
        self.culture_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.culture_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.culture_up.setObjectName("culture_up")
        self.sozid = QtWidgets.QLabel(self.centralwidget)
        self.sozid.setGeometry(QtCore.QRect(870, 370, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.sozid.setFont(font)
        self.sozid.setStyleSheet("background-color: #4b6154;\n"
"color:white;\n"
"border: 2px solid #c0dfc2; \n"
"border-radius: 10px;  ")
        self.sozid.setAlignment(QtCore.Qt.AlignCenter)
        self.sozid.setObjectName("sozid")
        self.culture_button = QtWidgets.QPushButton(self.centralwidget)
        self.culture_button.setGeometry(QtCore.QRect(870, 550, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.culture_button.setFont(font)
        self.culture_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.culture_button.setObjectName("culture_button")
        self.culture_tablo = QtWidgets.QLabel(self.centralwidget)
        self.culture_tablo.setGeometry(QtCore.QRect(1000, 550, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.culture_tablo.setFont(font)
        self.culture_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.culture_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.culture_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.culture_tablo.setObjectName("culture_tablo")
        self.fastfinger_button = QtWidgets.QPushButton(self.centralwidget)
        self.fastfinger_button.setGeometry(QtCore.QRect(870, 430, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.fastfinger_button.setFont(font)
        self.fastfinger_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.fastfinger_button.setObjectName("fastfinger_button")
        self.performance_tablo = QtWidgets.QLabel(self.centralwidget)
        self.performance_tablo.setGeometry(QtCore.QRect(1000, 610, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.performance_tablo.setFont(font)
        self.performance_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.performance_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.performance_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.performance_tablo.setObjectName("performance_tablo")
        self.fastfinger_tablo = QtWidgets.QLabel(self.centralwidget)
        self.fastfinger_tablo.setGeometry(QtCore.QRect(1000, 430, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.fastfinger_tablo.setFont(font)
        self.fastfinger_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fastfinger_tablo.setStyleSheet("background-color: #c0dfc2;\n"
"border: 2px solid #4b6154")
        self.fastfinger_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.fastfinger_tablo.setObjectName("fastfinger_tablo")
        self.barter_tablo = QtWidgets.QLabel(self.centralwidget)
        self.barter_tablo.setGeometry(QtCore.QRect(1000, 670, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(32)
        self.barter_tablo.setFont(font)
        self.barter_tablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.barter_tablo.setStyleSheet("background-color: #c0dfc2\n"
"")
        self.barter_tablo.setAlignment(QtCore.Qt.AlignCenter)
        self.barter_tablo.setObjectName("barter_tablo")
        self.barter_up = QtWidgets.QPushButton(self.centralwidget)
        self.barter_up.setGeometry(QtCore.QRect(1060, 670, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.barter_up.setFont(font)
        self.barter_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.barter_up.setStyleSheet("background-color:#94d6ba;\n"
"text-align: center")
        self.barter_up.setObjectName("barter_up")
        self.mecanica_button = QtWidgets.QPushButton(self.centralwidget)
        self.mecanica_button.setGeometry(QtCore.QRect(870, 490, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.mecanica_button.setFont(font)
        self.mecanica_button.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.mecanica_button.setObjectName("mecanica_button")
        self.answer = QtWidgets.QLabel(self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(470, 40, 201, 191))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(72)
        self.answer.setFont(font)
        self.answer.setStyleSheet("background-color: #4b6154;\n"
"color:white;\n"
"border: 2px solid #c0dfc2; \n"
"border-radius: 10px;  ")
        self.answer.setAlignment(QtCore.Qt.AlignCenter)
        self.answer.setObjectName("answer")
        self.just_1 = QtWidgets.QLabel(self.centralwidget)
        self.just_1.setGeometry(QtCore.QRect(30, 240, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.just_1.setFont(font)
        self.just_1.setObjectName("just_1")
        self.just_2 = QtWidgets.QLabel(self.centralwidget)
        self.just_2.setGeometry(QtCore.QRect(970, 230, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.just_2.setFont(font)
        self.just_2.setObjectName("just_2")
        self.just_3 = QtWidgets.QLabel(self.centralwidget)
        self.just_3.setGeometry(QtCore.QRect(320, 240, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.just_3.setFont(font)
        self.just_3.setObjectName("just_3")
        self.just_4 = QtWidgets.QLabel(self.centralwidget)
        self.just_4.setGeometry(QtCore.QRect(670, 230, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.just_4.setFont(font)
        self.just_4.setObjectName("just_4")
        self.sbros = QtWidgets.QPushButton(self.centralwidget)
        self.sbros.setGeometry(QtCore.QRect(40, 100, 131, 71))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.sbros.setFont(font)
        self.sbros.setStyleSheet("QPushButton {\n"
"    background-color: #c0dfc2; \n"
"    border-radius: 10px;  \n"
"    border: 2px solid #4b6154;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b6154;\n"
"    border: 2px solid #c0dfc2; \n"
"    color:white\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.sbros.setObjectName("sbros")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Toss cube"))
        self.poko.setText(_translate("MainWindow", "Покорение"))
        self.poko_tablo.setText(_translate("MainWindow", "0"))
        self.poko_down.setText(_translate("MainWindow", "♥"))
        self.poko_up.setText(_translate("MainWindow", "♠"))
        self.survival_up.setText(_translate("MainWindow", "♠"))
        self.survival_down.setText(_translate("MainWindow", "♥"))
        self.survival_tablo.setText(_translate("MainWindow", "0"))
        self.provorstvo_down.setText(_translate("MainWindow", "♥"))
        self.provorstvo_tablo.setText(_translate("MainWindow", "0"))
        self.provorstvo_up.setText(_translate("MainWindow", "♠"))
        self.samooblad_down.setText(_translate("MainWindow", "♥"))
        self.samooblad_tablo.setText(_translate("MainWindow", "0"))
        self.samooblad_up.setText(_translate("MainWindow", "♠"))
        self.threat_down.setText(_translate("MainWindow", "♥"))
        self.threat_tablo.setText(_translate("MainWindow", "0"))
        self.threat_up.setText(_translate("MainWindow", "♠"))
        self.atletic_down.setText(_translate("MainWindow", "♥"))
        self.atletic_tablo.setText(_translate("MainWindow", "0"))
        self.atletic_up.setText(_translate("MainWindow", "♠"))
        self.animal_down.setText(_translate("MainWindow", "♥"))
        self.animal_tablo.setText(_translate("MainWindow", "0"))
        self.animal_up.setText(_translate("MainWindow", "♠"))
        self.survival_button.setText(_translate("MainWindow", "Выживание"))
        self.provorstvo_button.setText(_translate("MainWindow", "Проворство"))
        self.samooblad_button.setText(_translate("MainWindow", "Самооблад"))
        self.threat_button.setText(_translate("MainWindow", "Угроза"))
        self.atletic_button.setText(_translate("MainWindow", "Атлетика"))
        self.animal_button.setText(_translate("MainWindow", "Животные"))
        self.pozn_up.setText(_translate("MainWindow", "♠"))
        self.ezoterica_button.setText(_translate("MainWindow", "Эзотерика"))
        self.history_button.setText(_translate("MainWindow", "История"))
        self.history_down.setText(_translate("MainWindow", "♥"))
        self.logic_up.setText(_translate("MainWindow", "♠"))
        self.logic_tablo.setText(_translate("MainWindow", "0"))
        self.pozn_down.setText(_translate("MainWindow", "♥"))
        self.learn_up.setText(_translate("MainWindow", "♠"))
        self.proniziat_tablo.setText(_translate("MainWindow", "0"))
        self.ezoterica_down.setText(_translate("MainWindow", "♥"))
        self.proniziat_up.setText(_translate("MainWindow", "♠"))
        self.history_up.setText(_translate("MainWindow", "♠"))
        self.ritor_down.setText(_translate("MainWindow", "♥"))
        self.proniziat_down.setText(_translate("MainWindow", "♥"))
        self.learn_down.setText(_translate("MainWindow", "♥"))
        self.logic_down.setText(_translate("MainWindow", "♥"))
        self.pozn_tablo.setText(_translate("MainWindow", "0"))
        self.logic_button.setText(_translate("MainWindow", "Логика"))
        self.ritor_up.setText(_translate("MainWindow", "♠"))
        self.pozn.setText(_translate("MainWindow", "Познание"))
        self.ritor_button.setText(_translate("MainWindow", "Риторика"))
        self.ritor_tablo.setText(_translate("MainWindow", "0"))
        self.learn_button.setText(_translate("MainWindow", "Изучение"))
        self.history_tablo.setText(_translate("MainWindow", "0"))
        self.learn_tablo.setText(_translate("MainWindow", "0"))
        self.ezoterica_tablo.setText(_translate("MainWindow", "0"))
        self.ezoterica_up.setText(_translate("MainWindow", "♠"))
        self.proniziat_button.setText(_translate("MainWindow", "Проницат"))
        self.save_up.setText(_translate("MainWindow", "♠"))
        self.focus_button.setText(_translate("MainWindow", "Внимател"))
        self.empatia_button.setText(_translate("MainWindow", "Эмпатия"))
        self.empatia_down.setText(_translate("MainWindow", "♥"))
        self.nature_up.setText(_translate("MainWindow", "♠"))
        self.nature_tablo.setText(_translate("MainWindow", "0"))
        self.save_down.setText(_translate("MainWindow", "♥"))
        self.medic_up.setText(_translate("MainWindow", "♠"))
        self.relig_tablo.setText(_translate("MainWindow", "0"))
        self.focus_down.setText(_translate("MainWindow", "♥"))
        self.relig_up.setText(_translate("MainWindow", "♠"))
        self.empatia_up.setText(_translate("MainWindow", "♠"))
        self.fraud_down.setText(_translate("MainWindow", "♥"))
        self.relig_down.setText(_translate("MainWindow", "♥"))
        self.medic_down.setText(_translate("MainWindow", "♥"))
        self.nature_down.setText(_translate("MainWindow", "♥"))
        self.save_tablo.setText(_translate("MainWindow", "0"))
        self.nature_button.setText(_translate("MainWindow", "Природа"))
        self.fraud_up.setText(_translate("MainWindow", "♠"))
        self.save.setText(_translate("MainWindow", "Сохранение"))
        self.fraud_button.setText(_translate("MainWindow", "Обман"))
        self.fraud_tablo.setText(_translate("MainWindow", "0"))
        self.medic_button.setText(_translate("MainWindow", "Медицина"))
        self.empatia_tablo.setText(_translate("MainWindow", "0"))
        self.medic_tablo.setText(_translate("MainWindow", "0"))
        self.focus_tablo.setText(_translate("MainWindow", "0"))
        self.focus_up.setText(_translate("MainWindow", "♠"))
        self.relig_button.setText(_translate("MainWindow", "Религия"))
        self.sozid_up.setText(_translate("MainWindow", "♠"))
        self.barter_button.setText(_translate("MainWindow", "Бартер"))
        self.performance_button.setText(_translate("MainWindow", "Выступление"))
        self.performance_down.setText(_translate("MainWindow", "♥"))
        self.craft_up.setText(_translate("MainWindow", "♠"))
        self.craft_tablo.setText(_translate("MainWindow", "0"))
        self.sozid_down.setText(_translate("MainWindow", "♥"))
        self.fastfinger_up.setText(_translate("MainWindow", "♠"))
        self.mecanica_tablo.setText(_translate("MainWindow", "0"))
        self.barter_down.setText(_translate("MainWindow", "♥"))
        self.mecanica_up.setText(_translate("MainWindow", "♠"))
        self.performance_up.setText(_translate("MainWindow", "♠"))
        self.culture_down.setText(_translate("MainWindow", "♥"))
        self.mecanica_down.setText(_translate("MainWindow", "♥"))
        self.fastfinger_down.setText(_translate("MainWindow", "♥"))
        self.craft_down.setText(_translate("MainWindow", "♥"))
        self.sozid_tablo.setText(_translate("MainWindow", "0"))
        self.craft_button.setText(_translate("MainWindow", "Ремесло"))
        self.culture_up.setText(_translate("MainWindow", "♠"))
        self.sozid.setText(_translate("MainWindow", "Cозидание"))
        self.culture_button.setText(_translate("MainWindow", "Культура"))
        self.culture_tablo.setText(_translate("MainWindow", "0"))
        self.fastfinger_button.setText(_translate("MainWindow", "Ловк. рук"))
        self.performance_tablo.setText(_translate("MainWindow", "0"))
        self.fastfinger_tablo.setText(_translate("MainWindow", "0"))
        self.barter_tablo.setText(_translate("MainWindow", "0"))
        self.barter_up.setText(_translate("MainWindow", "♠"))
        self.mecanica_button.setText(_translate("MainWindow", "Механика"))
        self.answer.setText(_translate("MainWindow", "0"))
        self.just_1.setText(_translate("MainWindow", "🎲"))
        self.just_2.setText(_translate("MainWindow", "🎲"))
        self.just_3.setText(_translate("MainWindow", "🎲"))
        self.just_4.setText(_translate("MainWindow", "🎲"))
        self.sbros.setText(_translate("MainWindow", "Сброс бросков"))

        self.animal_button.clicked.connect(self.show_answer_for_animal)
        self.animal_up.clicked.connect(self.plus_animal)
        self.animal_down.clicked.connect(self.minus_animal)

        self.atletic_button.clicked.connect(self.show_answer_for_atletic)
        self.atletic_up.clicked.connect(self.plus_atletic)
        self.atletic_down.clicked.connect(self.minus_atletic)

        self.threat_button.clicked.connect(self.show_answer_for_threat)
        self.threat_up.clicked.connect(self.plus_threat)
        self.threat_down.clicked.connect(self.minus_threat)


        self.survival_button.clicked.connect(self.show_answer_for_survival)
        self.survival_up.clicked.connect(self.plus_survival)
        self.survival_down.clicked.connect(self.minus_survival)
        

        self.provorstvo_button.clicked.connect(self.show_answer_for_provorstvo)
        self.provorstvo_up.clicked.connect(self.plus_provorstvo)
        self.provorstvo_down.clicked.connect(self.minus_provorstvo)

        

        self.samooblad_button.clicked.connect(self.show_answer_for_samooblad)
        self.samooblad_up.clicked.connect(self.plus_samooblad)
        self.samooblad_down.clicked.connect(self.minus_samooblad)


        self.poko_down.clicked.connect(self.minus_poko)
        self.poko_up.clicked.connect(self.plus_poko)


        self.sbros.clicked.connect(self.SBROS)
        

        self.learn_button.clicked.connect(self.show_answer_for_learn)
        self.learn_up.clicked.connect(self.plus_learn)
        self.learn_down.clicked.connect(self.minus_learn)

        self.proniziat_button.clicked.connect(self.show_answer_for_proniziat)
        self.proniziat_up.clicked.connect(self.plus_proniziat)
        self.proniziat_down.clicked.connect(self.minus_proniziat)

        self.ritor_button.clicked.connect(self.show_answer_for_ritor)
        self.ritor_up.clicked.connect(self.plus_ritor)
        self.ritor_down.clicked.connect(self.minus_ritor)


        self.history_button.clicked.connect(self.show_answer_for_history)
        self.history_up.clicked.connect(self.plus_history)
        self.history_down.clicked.connect(self.minus_history)
        

        self.ezoterica_button.clicked.connect(self.show_answer_for_ezoterica)
        self.ezoterica_up.clicked.connect(self.plus_ezoterica)
        self.ezoterica_down.clicked.connect(self.minus_ezoterica)


        self.logic_button.clicked.connect(self.show_answer_for_logic)
        self.logic_up.clicked.connect(self.plus_logic)
        self.logic_down.clicked.connect(self.minus_logic)


        self.pozn_down.clicked.connect(self.minus_pozn)
        self.pozn_up.clicked.connect(self.plus_pozn)


  #///////////////////////////SAVE/////////////////////////////////////////////////

        self.save_down.clicked.connect(self.minus_save)
        self.save_up.clicked.connect(self.plus_save)

        self.relig_button.clicked.connect(self.show_answer_for_relig)
        self.relig_up.clicked.connect(self.plus_relig)
        self.relig_down.clicked.connect(self.minus_relig)

        self.fraud_button.clicked.connect(self.show_answer_for_fraud)
        self.fraud_up.clicked.connect(self.plus_fraud)
        self.fraud_down.clicked.connect(self.minus_fraud)


        self.empatia_button.clicked.connect(self.show_answer_for_empatia)
        self.empatia_up.clicked.connect(self.plus_empatia)
        self.empatia_down.clicked.connect(self.minus_empatia)
        
        self.medic_button.clicked.connect(self.show_answer_for_medic)
        self.medic_up.clicked.connect(self.plus_medic)
        self.medic_down.clicked.connect(self.minus_medic)

        self.focus_button.clicked.connect(self.show_answer_for_focus)
        self.focus_up.clicked.connect(self.plus_focus)
        self.focus_down.clicked.connect(self.minus_focus)


        self.nature_button.clicked.connect(self.show_answer_for_nature)
        self.nature_up.clicked.connect(self.plus_nature)
        self.nature_down.clicked.connect(self.minus_nature)

#////////////////////////////////////////////////////////////////////////////

#////////////////////////////SOZIDANIE////////////////////////////////////////////////
        self.craft_button.clicked.connect(self.show_answer_for_craft)
        self.craft_up.clicked.connect(self.plus_craft)
        self.craft_down.clicked.connect(self.minus_craft)

        self.barter_button.clicked.connect(self.show_answer_for_barter)
        self.barter_up.clicked.connect(self.plus_barter)
        self.barter_down.clicked.connect(self.minus_barter)

        self.performance_button.clicked.connect(self.show_answer_for_performance)
        self.performance_up.clicked.connect(self.plus_performance)
        self.performance_down.clicked.connect(self.minus_performance)


        self.culture_button.clicked.connect(self.show_answer_for_culture)
        self.culture_up.clicked.connect(self.plus_culture)
        self.culture_down.clicked.connect(self.minus_culture)
        

        self.mecanica_button.clicked.connect(self.show_answer_for_mecanica)
        self.mecanica_up.clicked.connect(self.plus_mecanica)
        self.mecanica_down.clicked.connect(self.minus_mecanica)

        

        self.fastfinger_button.clicked.connect(self.show_answer_for_fastfinger)
        self.fastfinger_up.clicked.connect(self.plus_fastfinger)
        self.fastfinger_down.clicked.connect(self.minus_fastfinger)


        self.sozid_down.clicked.connect(self.minus_sozid)
        self.sozid_up.clicked.connect(self.plus_sozid)

    
    def SBROS(self):
        self.answer.setText("0")
#////////////////////////POKORENIE////////////////////////////////////////////////////
    def plus_samooblad(self):
        a= int(self.samooblad_tablo.text())
        a+=1
        self.samooblad_tablo.setText(str(a))

    def minus_samooblad(self):
        a= int(self.samooblad_tablo.text())
        a-=1
        if(a<0):
            return
        self.samooblad_tablo.setText(str(a))
    def show_answer_for_samooblad(self):
        one =  int(self.poko_tablo.text())
        two = int(self.samooblad_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))



    def plus_provorstvo(self):
        a= int(self.provorstvo_tablo.text())
        a+=1
        self.provorstvo_tablo.setText(str(a))
    def minus_provorstvo(self):
        a= int(self.provorstvo_tablo.text())
        a-=1
        if(a<0):
            return
        self.provorstvo_tablo.setText(str(a))
    def show_answer_for_provorstvo(self):
        one =  int(self.poko_tablo.text())
        two = int(self.provorstvo_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))




    def plus_survival(self):
        a= int(self.survival_tablo.text())
        a+=1
        self.survival_tablo.setText(str(a))
    def minus_survival(self):
        a= int(self.survival_tablo.text())
        a-=1
        if(a<0):
            return
        self.survival_tablo.setText(str(a))
    def show_answer_for_survival(self):
        one =  int(self.poko_tablo.text())
        two = int(self.survival_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    def plus_threat(self):
        a= int(self.threat_tablo.text())
        a+=1
        self.threat_tablo.setText(str(a))
    def minus_threat(self):
        a= int(self.threat_tablo.text())
        a-=1
        if(a<0):
            return
        self.threat_tablo.setText(str(a))
    def show_answer_for_threat(self):
        one =  int(self.poko_tablo.text())
        two = int(self.threat_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    def plus_poko(self):
        a= int(self.poko_tablo.text())
        a+=1
        self.poko_tablo.setText(str(a))
    def minus_poko(self):
        a= int(self.poko_tablo.text())
        a-=1
        if(a<0):
            return
        self.poko_tablo.setText(str(a))




    def plus_animal(self):
        a= int(self.animal_tablo.text())
        a+=1
        self.animal_tablo.setText(str(a))
    def minus_animal(self):
        a= int(self.animal_tablo.text())
        a-=1
        if(a<0):
            return
        self.animal_tablo.setText(str(a))
    def show_answer_for_animal(self):
        one =  int(self.poko_tablo.text())
        two = int(self.animal_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    


    def plus_atletic(self):
        a= int(self.atletic_tablo.text())
        a+=1
        self.atletic_tablo.setText(str(a))
    def minus_atletic(self):
        a= int(self.atletic_tablo.text())
        a-=1
        if(a<0):
            return
        self.atletic_tablo.setText(str(a))
    def show_answer_for_atletic(self):
        one =  int(self.poko_tablo.text())
        two = int(self.atletic_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))
#////////////////////////////////////////////////////////////////////////////

#///////////////////////////POZNANIE/////////////////////////////////////////////////        
    def plus_logic(self):
        a= int(self.logic_tablo.text())
        a+=1
        self.logic_tablo.setText(str(a))
    def minus_logic(self):
        a= int(self.logic_tablo.text())
        a-=1
        if(a<0):
            return
        self.logic_tablo.setText(str(a))
    def show_answer_for_logic(self):
        one =  int(self.pozn_tablo.text())
        two = int(self.logic_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))



    def plus_ezoterica(self):
        a= int(self.ezoterica_tablo.text())
        a+=1
        self.ezoterica_tablo.setText(str(a))
    def minus_ezoterica(self):
        a= int(self.ezoterica_tablo.text())
        a-=1
        if(a<0):
            return
        self.ezoterica_tablo.setText(str(a))
    def show_answer_for_ezoterica(self):
        one =  int(self.pozn_tablo.text())
        two = int(self.ezoterica_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))




    def plus_history(self):
        a= int(self.history_tablo.text())
        a+=1
        self.history_tablo.setText(str(a))
    def minus_history(self):
        a= int(self.history_tablo.text())
        a-=1
        if(a<0):
            return
        self.history_tablo.setText(str(a))
    def show_answer_for_history(self):
        one =  int(self.pozn_tablo.text())
        two = int(self.history_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    def plus_ritor(self):
        a= int(self.ritor_tablo.text())
        a+=1
        self.ritor_tablo.setText(str(a))
    def minus_ritor(self):
        a= int(self.ritor_tablo.text())
        a-=1
        if(a<0):
            return
        self.ritor_tablo.setText(str(a))
    def show_answer_for_ritor(self):
        one =  int(self.pozn_tablo.text())
        two = int(self.ritor_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))



    def plus_pozn(self):
        a= int(self.pozn_tablo.text())
        a+=1
        self.pozn_tablo.setText(str(a))
    def minus_pozn(self):
        a= int(self.pozn_tablo.text())
        a-=1
        if(a<0):
            return
        self.pozn_tablo.setText(str(a))




    def plus_learn(self):
        a= int(self.learn_tablo.text())
        a+=1
        self.learn_tablo.setText(str(a))
    def minus_learn(self):
        a= int(self.learn_tablo.text())
        a-=1
        if(a<0):
            return
        self.learn_tablo.setText(str(a))
    def show_answer_for_learn(self):
        one =  int(self.pozn_tablo.text())
        two = int(self.learn_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))
    


    def plus_proniziat(self):
        a= int(self.proniziat_tablo.text())
        a+=1
        self.proniziat_tablo.setText(str(a))
    def minus_proniziat(self):
        a= int(self.proniziat_tablo.text())
        a-=1
        if(a<0):
            return
        self.proniziat_tablo.setText(str(a))
    def show_answer_for_proniziat(self):
        one =  int(self.pozn_tablo.text())
        two = int(self.proniziat_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))
    

#////////////////////////////////////////////////////////////////////////////


#///////////////////////////SAVE/////////////////////////////////////////////////
    def plus_nature(self):
        a= int(self.nature_tablo.text())
        a+=1
        self.nature_tablo.setText(str(a))
    def minus_nature(self):
        a= int(self.nature_tablo.text())
        a-=1
        if(a<0):
            return
        self.nature_tablo.setText(str(a))
    def show_answer_for_nature(self):
        one =  int(self.save_tablo.text())
        two = int(self.nature_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))



    def plus_focus(self):
        a= int(self.focus_tablo.text())
        a+=1
        self.focus_tablo.setText(str(a))
    def minus_focus(self):
        a= int(self.focus_tablo.text())
        a-=1
        if(a<0):
            return
        self.focus_tablo.setText(str(a))
    def show_answer_for_focus(self):
        one =  int(self.save_tablo.text())
        two = int(self.focus_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))




    def plus_empatia(self):
        a= int(self.empatia_tablo.text())
        a+=1
        self.empatia_tablo.setText(str(a))
    def minus_empatia(self):
        a= int(self.empatia_tablo.text())
        a-=1
        if(a<0):
            return
        self.empatia_tablo.setText(str(a))
    def show_answer_for_empatia(self):
        one =  int(self.save_tablo.text())
        two = int(self.empatia_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    def plus_fraud(self):
        a= int(self.fraud_tablo.text())
        a+=1
        self.fraud_tablo.setText(str(a))
    def minus_fraud(self):
        a= int(self.fraud_tablo.text())
        a-=1
        if(a<0):
            return
        self.fraud_tablo.setText(str(a))
    def show_answer_for_fraud(self):
        one =  int(self.save_tablo.text())
        two = int(self.fraud_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    def plus_save(self):
        a= int(self.save_tablo.text())
        a+=1
        self.save_tablo.setText(str(a))
    def minus_save(self):
        a= int(self.save_tablo.text())
        a-=1
        if(a<0):
            return
        self.save_tablo.setText(str(a))




    def plus_medic(self):
        a= int(self.medic_tablo.text())
        a+=1
        self.medic_tablo.setText(str(a))
    def minus_medic(self):
        a= int(self.medic_tablo.text())
        a-=1
        if(a<0):
            return
        self.medic_tablo.setText(str(a))
    def show_answer_for_medic(self):
        one =  int(self.save_tablo.text())
        two = int(self.medic_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    


    def plus_relig(self):
        a= int(self.relig_tablo.text())
        a+=1
        self.relig_tablo.setText(str(a))
    def minus_relig(self):
        a= int(self.relig_tablo.text())
        a-=1
        if(a<0):
            return
        self.relig_tablo.setText(str(a))
    def show_answer_for_relig(self):
        one =  int(self.save_tablo.text())
        two = int(self.relig_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))
#////////////////////////////////////////////////////////////////////////////
#//////////////////////////////////SOZIDANIE//////////////////////////////////////////
    def plus_fastfinger(self):
        a= int(self.fastfinger_tablo.text())
        a+=1
        self.fastfinger_tablo.setText(str(a))

    def minus_fastfinger(self):
        a= int(self.fastfinger_tablo.text())
        a-=1
        if(a<0):
            return
        self.fastfinger_tablo.setText(str(a))
    def show_answer_for_fastfinger(self):
        one =  int(self.sozid_tablo.text())
        two = int(self.fastfinger_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))



    def plus_mecanica(self):
        a= int(self.mecanica_tablo.text())
        a+=1
        self.mecanica_tablo.setText(str(a))
    def minus_mecanica(self):
        a= int(self.mecanica_tablo.text())
        a-=1
        if(a<0):
            return
        self.mecanica_tablo.setText(str(a))
    def show_answer_for_mecanica(self):
        one =  int(self.sozid_tablo.text())
        two = int(self.mecanica_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))




    def plus_culture(self):
        a= int(self.culture_tablo.text())
        a+=1
        self.culture_tablo.setText(str(a))
    def minus_culture(self):
        a= int(self.culture_tablo.text())
        a-=1
        if(a<0):
            return
        self.culture_tablo.setText(str(a))
    def show_answer_for_culture(self):
        one =  int(self.sozid_tablo.text())
        two = int(self.culture_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    def plus_performance(self):
        a= int(self.performance_tablo.text())
        a+=1
        self.performance_tablo.setText(str(a))
    def minus_performance(self):
        a= int(self.performance_tablo.text())
        a-=1
        if(a<0):
            return
        self.performance_tablo.setText(str(a))
    def show_answer_for_performance(self):
        one =  int(self.sozid_tablo.text())
        two = int(self.performance_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    def plus_sozid(self):
        a= int(self.sozid_tablo.text())
        a+=1
        self.sozid_tablo.setText(str(a))
    def minus_sozid(self):
        a= int(self.sozid_tablo.text())
        a-=1
        if(a<0):
            return
        self.sozid_tablo.setText(str(a))




    def plus_craft(self):
        a= int(self.craft_tablo.text())
        a+=1
        self.craft_tablo.setText(str(a))
    def minus_craft(self):
        a= int(self.craft_tablo.text())
        a-=1
        if(a<0):
            return
        self.craft_tablo.setText(str(a))
    def show_answer_for_craft(self):
        one =  int(self.sozid_tablo.text())
        two = int(self.craft_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    


    def plus_barter(self):
        a= int(self.barter_tablo.text())
        a+=1
        self.barter_tablo.setText(str(a))
    def minus_barter(self):
        a= int(self.barter_tablo.text())
        a-=1
        if(a<0):
            return
        self.barter_tablo.setText(str(a))
    def show_answer_for_barter(self):
        one =  int(self.sozid_tablo.text())
        two = int(self.barter_tablo.text())
        ans = system_iaros(one, two)
        three= int(self.answer.text())
        self.answer.setText(str(ans+three))

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
